import type { Vehicle } from './types/vehicle'

export const mockVehicles: Vehicle[] = [
  {
    id: '1',
    slug: 'suzuki-every-2022',
    brand: 'Suzuki',
    model: 'Every',
    year: 2022,
    transmission: 'Automatic',
    mileageKm: 21000,
    category: 'Mini Van',
    status: 'available',
    featured: true,
    image: '/mock-car.png',
  },
  {
    id: '2',
    slug: 'nissan-nv100-2021',
    brand: 'Nissan',
    model: 'NV100',
    year: 2021,
    transmission: 'Automatic',
    mileageKm: 18500,
    category: 'Mini Van',
    status: 'available',
    featured: true,
    image: '/mock-car.png',
  },
  {
    id: '3',
    slug: 'daihatsu-hijet-2021',
    brand: 'Daihatsu',
    model: 'Hijet',
    year: 2021,
    transmission: 'Automatic',
    mileageKm: 19200,
    category: 'Mini Van',
    status: 'sold',
    featured: false,
    image: '/mock-car.png',
  },
  {
    id: '4',
    slug: 'suzuki-carry-2020',
    brand: 'Suzuki',
    model: 'Carry',
    year: 2020,
    transmission: 'Manual',
    mileageKm: 34000,
    category: 'Multi-Cab',
    status: 'available',
    featured: false,
    image: '/mock-car.png',
  },
  {
    id: '5',
    slug: 'toyota-hiace-2019',
    brand: 'Toyota',
    model: 'HiAce',
    year: 2019,
    transmission: 'Manual',
    mileageKm: 78000,
    category: 'Van',
    status: 'available',
    featured: false,
    image: '/mock-car.png',
  },
  {
    id: '6',
    slug: 'mitsubishi-canter-2018',
    brand: 'Mitsubishi',
    model: 'Fuso Canter',
    year: 2018,
    transmission: 'Manual',
    mileageKm: 96000,
    category: 'Truck',
    status: 'sold',
    featured: false,
    image: '/mock-car.png',
  },
]
